trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - pom.xml

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
  
  - task: PowerShell@2 
    displayName: Download Qwiet cli
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile $(Agent.HomeDirectory)\sl.zip
        Expand-Archive -Path $(Agent.HomeDirectory)\sl.zip -DestinationPath $(Agent.HomeDirectory) -Force\
      errorActionPreference: 'continue'
      warningPreference: 'continue'
      informationPreference: 'continue'
      pwsh: true
      
  - task: JavaToolInstaller@0
    inputs:
     versionSpec: '8'
     jdkArchitectureOption: 'x64'
     jdkSourceOption: 'PreInstalled'

  - task: CmdLine@2
    displayName: Analyze with preZero
    inputs:
     script: |
      $(Agent.HomeDirectory)\sl.exe analyze --app ShiftLeftJavaAzWin --tag branch=$(Build.SourceBranchName) --java target/hello-shiftleft-0.0.1.jar
     workingDirectory: '$(Build.SourcesDirectory)'
    env:
      SHIFTLEFT_ACCESS_TOKEN: $(shiftleft_access_token)

#    - task: ShiftLeftScan@1
#    inputs:
#      organization: 'your-shiftleft-organization'
#      project: 'your-shiftleft-project'
#      repository: 'your-azure-repo'
#     scanType: 'full'
#      failOnError: true
