trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - pom.xml

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
  
  - task: PowerShell@2 
    displayName: Download Shiftleft cli
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile $(Agent.HomeDirectory)\sl.zip
        Expand-Archive -Path $(Agent.HomeDirectory)\sl.zip -DestinationPath $(Agent.HomeDirectory)
      errorActionPreference: 'continue'
      warningPreference: 'continue'
      informationPreference: 'continue'
      pwsh: true
     
  - task: JavaToolInstaller@0
    inputs:
     versionSpec: '8'
     jdkArchitectureOption: 'x64'
     jdkSourceOption: 'PreInstalled'

  - task: CmdLine@2
    displayName: Analyze with preZero
    inputs:
     script: |
      $(Agent.HomeDirectory)\sl.exe analyze --wait --app ShiftLeftJavaAzWin --tag branch=$(System.DefaultWorkingDirectory) --java target/hello-shiftleft-0.0.1.jar
     workingDirectory: '$(System.DefaultWorkingDirectory)'
    env:
      SHIFTLEFT_ACCESS_TOKEN: $(shiftleft_access_token)
       shiftleft auth login --apiKey API_token
       shiftleft analyze --path $(System.DefaultWorkingDirectory)