trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - pom.xml

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
- group: shiftleft-token

steps:
  
  - task: PowerShell@2 
    displayName: Download Shiftleft cli
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile $(Agent.HomeDirectory)\sl.zip
        Expand-Archive -Path $(Agent.HomeDirectory)\sl.zip -DestinationPath $(Agent.HomeDirectory)
      errorActionPreference: 'continue'
      warningPreference: 'continue'
      informationPreference: 'continue'
      pwsh: true
     
  - task: JavaToolInstaller@0
    inputs:
     versionSpec: '8'
     jdkArchitectureOption: 'x64'
     jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    inputs:
     mavenPomFile: '$(System.DefaultWorkingDirectory)/Backend/pom.xml'
     mavenOptions: '-Xmx3072m'
     javaHomeOption: 'JDKVersion'
     jdkVersionOption: '1.8'
     jdkArchitectureOption: 'x64'
     publishJUnitResults: true
     goals: 'clean package'

  - task: CmdLine@2
    displayName: Analyze with preZero
    inputs:
     script: |
      $(Agent.HomeDirectory)\sl.exe analyze --wait --app TarunS28.IncShiftMate-final --tag branch=$(Build.SourceBranchName) --java target/hello-shiftleft-0.0.1.jar
     workingDirectory: '$(System.DefaultWorkingDirectory)'
    env:
      SHIFTLEFT_ACCESS_TOKEN: $(SHIFTLEFT_ACCESS_TOKEN)
       shiftleft auth login --apiKey API_token
       shiftleft analyze --language java --path $(System.DefaultWorkingDirectory)